apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  labels:
    app: blockchain-service
spec:
  type: NodePort
  selector:
    app: blockchain-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001
    nodePort: 30001